version: '3.7'
services:
  swagger:
    image: swaggerapi/swagger-ui
    container_name: polito_tm_api_swagger
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /openapi.yaml
    volumes:
      - ./openapi.yaml:/openapi.yaml
